apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-green
  labels:
    app: hello-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-green
  template:
    metadata:
      name: hello-green
      labels:
        app: hello-green
    spec:
      containers:
      - name: hello-world
        image: phalligan/capstone:0.0.2
        imagePullPolicy: Always
        ports:
         - containerPort: 8081


