apiVersion: v1
kind: Service
metadata: 
  name:  hello-green
  labels: 
    name:  hello-green
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8001
  selector: 
    app: hello-green
  type: LoadBalancer