# Ansible playbook AWS - install docker
---
- name: "AWS - Install docker"
  hosts: all
  remote_user: ec2-user
  tasks:
    - block:
      - name: Update all packages
        yum:
          name: '*'
          state: latest
          update_only: yes

      - name: Ensure a list of yum packages are installed
        yum:
          name: "{{ packages }}"
          state: latest
          update_cache: yes
        vars:
          packages:
          - python3
          - python3-pip
          - python3-setuptools
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - docker
        become: yes

      - name: add user to docker group 
        user:
          name: ec2-user
          groups: docker
          append: yes

      - name: Enable Docker CE service at startup
        service:
          name: docker
          state: started
          enabled: yes
      become: true